site_name: Pure Data Structures
site_description: Pure Data Structures documentation
theme: readthedocs
nav:
  - Usage: usage.md
  - Drawbacks : drawbacks.md
  - Release Note : releases.md
  - References : references.md
  - Development : development.md
  - Purposes : purposes.md

extra:
    version: 1.0

use_directory_urls: true

markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
        baselevel: 2

plugins:
    - search

repo_name: 'sodrooome/pure-datastructures'
repo_url: 'https://github.com/sodrooome/pure-datastructures'
edit_uri: ""


